version: '3.8'

services:
  db:
    image: postgres:12
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:${POSTGRES_PORT}'
    networks:
      - postgres
    restart: unless-stopped

volumes:
  data:

networks:
  postgres:
    driver: bridge
